name: Build with Hugo

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        hugo-version:
          - 'latest'
          - '0.85.0' # MinVersion
          - '0.88.1' # Consistent with local-dev version
    steps:
      - uses: actions/checkout@v2

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: ${{ matrix.hugo-version }}
          extended: true

      - name: Test Example Site
        run: make test THEME_NAME=explorer-hugo-theme
